O-D Array

In [2]:
import numpy as np

x = np.array(42)

print(x)

42


1-D Array

In [4]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])

print(x)

[1 2 3 4 5]


2-D Array

In [5]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])

print(x)

[[1 2 3]
 [4 5 6]]


In [ ]:
3-D Array

In [6]:
import numpy as np

x = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(x)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Checking Dimension

In [7]:
print(x.ndim)

3
