In [2]:
# Import the necessary libraries
from PIL import Image
from numpy import asarray


# load the image and convert into
# numpy array
x = Image.open('hi.png')
x_array = asarray(x)

# data
print(x_array)

[[[ 74  17  14 255]
  [ 92  29  30 255]
  [ 89  20  23 255]
  ...
  [  5 140 249 255]
  [  5 138 248 255]
  [  5 138 248 255]]

 [[ 74  17  14 255]
  [ 95  31  32 255]
  [ 91  22  25 255]
  ...
  [ 19 121 237 255]
  [ 10 129 250 255]
  [  0 141 253 255]]

 [[ 70  14  10 255]
  [ 92  29  30 255]
  [ 93  25  27 255]
  ...
  [ 85 173 248 255]
  [  0  69 164 255]
  [  0 120 232 255]]

 ...

 [[250   0   2 255]
  [248   0   2 255]
  [248   0   2 255]
  ...
  [254  71  19 255]
  [254  71  19 255]
  [254  71  19 255]]

 [[255   0   9 255]
  [255   0   9 255]
  [255   0   9 255]
  ...
  [255  70  20 255]
  [255  70  22 255]
  [255  70  22 255]]

 [[224  21   0 255]
  [224  21   0 255]
  [224  21   0 255]
  ...
  [233  83   0 255]
  [233  83   0 255]
  [233  83   0 255]]]


In [3]:
print(x_array.shape)


(206, 435, 4)


Multi Array to 0-D Flatten

In [5]:
x_flat = x_array.reshape(-1)

print(x_flat)

[ 74  17  14 ...  83   0 255]
