In [7]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(x)



[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
x_reshape = x.reshape(4, 3)

print(x_reshape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
x_reshape = x.reshape(2, 3, 2)

print(x_reshape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
